version: "3.7"

services:

  mysql:
    container_name: cfsolana-mysql
    image: mysql
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
    ports: 
      - "3307:3307"
 
  cf-solana:
    container_name: cfsolana-lucee
    build: .
    tty: true
    ports:
      - "8080:8080"
      - "8443:8443"
    env_file: ./.env
    environment:
      DB_BUNDLENAME: ${DB_BUNDLENAME}
      DB_BUNDLEVERSION: ${DB_BUNDLEVERSION}
      DB_CLASS: ${DB_CLASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
    volumes:
      - ../config:/app/config
      # contentbox overwrites our config on new install
      # we will copy over ours after the install
      - ../config:/tmp/config
      - ../handlers:/app/handlers
      - ../layouts:/app/layouts
      - ../models:/app/models
      - ../modules_app:/app/modules_app
      - ../views:/app/views
      - ../.cfconfig:/app/.cfconfig
      - ../Application.cfc:/app/Application.cfc
      - ../box.json:/app/box.json
      - ../index.cfm:/app/index.cfm
      - ../server.json:/app/server.json